# Generated by Django 3.1.5 on 2021-01-31 02:56

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='nombre de usuario')),
                ('content', models.TextField(verbose_name='contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'susurro',
                'verbose_name_plural': 'susurros',
            },
        ),
    ]
